In [3]:
import pandas as pd
df=pd.read_excel("movies_db.xlsx","financials")
df_m=pd.read_excel("movies_db.xlsx","movies")
print(df)
print(df_m)

    movie_id    budget   revenue       unit currency
0        101      1.00      12.5   Billions      INR
1        102    200.00     954.8   Millions      USD
2        103    165.00     644.8   Millions       $$
3        104    180.00     854.0   Millions  Dollars
4        105    250.00     670.0   Millions      USD
5        107    400.00    2000.0   Millions      INR
6        108    550.00    4000.0   Millions      INR
7        109    390.00    1360.0   Millions      INR
8        110      1.40       3.5   Billions      INR
9        111     25.00      73.3   Millions      USD
10       113    165.00     701.8   Millions      USD
11       114    205.00     365.3   Millions      USD
12       115     55.00     307.1   Millions      USD
13       116    103.00     460.5   Millions      USD
14       117    200.00    2202.0   Millions      USD
15       118      3.18       3.3   Millions      USD
16       119    237.00    2847.0   Millions      USD
17       120      7.20     291.0   Millions      USD
18       121    185.00    1006.0   Millions      USD
19       122     22.00     322.2   Millions      USD
20       123     63.00    1046.0   Millions      USD
21       124     15.50     263.1   Millions      USD
22       125    400.00    2798.0   Millions      USD
23       126    400.00    2048.0   Millions      USD
24       127  70000.00  100000.0  Thousands      INR
25       128    120.00    1350.0   Millions      INR
26       129    100.00     410.0   Millions      INR
27       130    850.00    8540.0   Millions      INR
28       131      1.00       5.9   Billions      INR
29       132      2.00       3.6   Billions      INR
30       133      5.50      12.0   Billions      INR
31       134      1.80       6.5   Billions      INR
32       135    250.00    3409.0   Millions      INR
33       136    900.00   11690.0   Millions      INR
34       137    216.70     370.6   Millions      USD
35       138    177.00     714.4   Millions      USD
36       139      1.80       3.1   Billions      INR
37       140    500.00     950.0   Millions      INR
38       406     30.00     350.0   Millions      INR
39       412    160.00     836.8   Millions      USD
    movie_id                                        title   industry  \
0        101                             K.G.F: Chapter 2  Bollywood
1        102  Doctor Strange in the Multiverse of Madness  Hollywood
2        103                        Thor: The Dark World   Hollywood
3        104                              Thor: Ragnarok   Hollywood
4        105                      Thor: Love and Thunder   Hollywood
5        106                                       Sholay  Bollywood
6        107                  Dilwale Dulhania Le Jayenge  Bollywood
7        108                                     3 Idiots  Bollywood
8        109                     Kabhi Khushi Kabhie Gham  Bollywood
9        110                             Bajirao Mastani   Bollywood
10       111                     The Shawshank Redemption  Hollywood
11       112                                    Inception  Hollywood
12       113                                 Interstellar  Hollywood
13       115                     The Pursuit of Happyness  Hollywood
14       116                                    Gladiator  Hollywood
15       117                                      Titanic  Hollywood
16       118                        It's a Wonderful Life  Hollywood
17       119                                       Avatar  Hollywood
18       120                                The Godfather  Hollywood
19       121                              The Dark Knight  Hollywood
20       122                             Schindler's List  Hollywood
21       123                                Jurassic Park  Hollywood
22       124                                     Parasite  Hollywood
23       125                            Avengers: Endgame  Hollywood
24       126                       Avengers: Infinity War  Hollywood
25       127                              Pather Panchali  Bollywood
26       128                             Taare Zameen Par  Bollywood
27       129                          Munna Bhai M.B.B.S.  Bollywood
28       130                                           PK  Bollywood
29       131                                        Sanju  Bollywood
30       132                    Pushpa: The Rise - Part 1  Bollywood
31       133                                          RRR  Bollywood
32       134                     Baahubali: The Beginning  Bollywood
33       135                            The Kashmir Files  Bollywood
34       136                            Bajrangi Bhaijaan  Bollywood
35       137           Captain America: The First Avenger  Hollywood
36       138          Captain America: The Winter Soldier  Hollywood
37       139                                       Race 3  Bollywood
38       140                                    Shershaah  Bollywood

    release_year  imdb_rating                     studio  language_id
0           2022          8.4              Hombale Films            3
1           2022          7.0             Marvel Studios            5
2           2013          6.8             Marvel Studios            5
3           2017          7.9             Marvel Studios            5
4           2022          6.8             Marvel Studios            5
5           1975          8.1           United Producers            1
6           1995          8.0             Yash Raj Films            1
7           2009          8.4         Vinod Chopra Films            1
8           2001          7.4         Dharma Productions            1
9           2015          7.2                        NaN            1
10          1994          9.3  Castle Rock Entertainment            5
11          2010          8.8      Warner Bros. Pictures            5
12          2014          8.6      Warner Bros. Pictures            5
13          2006          8.0          Columbia Pictures            5
14          2000          8.5       Universal Pictures              5
15          1997          7.9         Paramount Pictures            5
16          1946          8.6              Liberty Films            5
17          2009          7.8           20th Century Fox            5
18          1972          9.2         Paramount Pictures            5
19          2008          9.0                    Syncopy            5
20          1993          9.0         Universal Pictures            5
21          1993          8.2         Universal Pictures            5
22          2019          8.5                        NaN            5
23          2019          8.4             Marvel Studios            5
24          2018          8.4             Marvel Studios            5
25          1955          8.3  Government of West Bengal            7
26          2007          8.3                        NaN            1
27          2003          8.1   Vinod Chopra Productions            1
28          2014          8.1         Vinod Chopra Films            1
29          2018          NaN         Vinod Chopra Films            1
30          2021          7.6        Mythri Movie Makers            2
31          2022          8.0          DVV Entertainment            2
32          2015          8.0           Arka Media Works            2
33          2022          8.3                Zee Studios            1
34          2015          8.1          Salman Khan Films            1
35          2011          6.9             Marvel Studios            5
36          2014          7.8             Marvel Studios            5
37          2018          1.9          Salman Khan Films            1
38          2021          8.4         Dharma Productions            1

In [4]:
def fun(x):
    if x=="$$" or x=="Dollars":
        return "USD"
    return x

# now to convert any specific value to some other values then we need to use converters function 

df1=pd.read_excel("movies_db.xlsx","financials",converters={
    'currency':fun
})
print(df1)

    movie_id    budget   revenue       unit currency
0        101      1.00      12.5   Billions      INR
1        102    200.00     954.8   Millions      USD
2        103    165.00     644.8   Millions      USD
3        104    180.00     854.0   Millions      USD
4        105    250.00     670.0   Millions      USD
5        107    400.00    2000.0   Millions      INR
6        108    550.00    4000.0   Millions      INR
7        109    390.00    1360.0   Millions      INR
8        110      1.40       3.5   Billions      INR
9        111     25.00      73.3   Millions      USD
10       113    165.00     701.8   Millions      USD
11       114    205.00     365.3   Millions      USD
12       115     55.00     307.1   Millions      USD
13       116    103.00     460.5   Millions      USD
14       117    200.00    2202.0   Millions      USD
15       118      3.18       3.3   Millions      USD
16       119    237.00    2847.0   Millions      USD
17       120      7.20     291.0   Millions      USD
18       121    185.00    1006.0   Millions      USD
19       122     22.00     322.2   Millions      USD
20       123     63.00    1046.0   Millions      USD
21       124     15.50     263.1   Millions      USD
22       125    400.00    2798.0   Millions      USD
23       126    400.00    2048.0   Millions      USD
24       127  70000.00  100000.0  Thousands      INR
25       128    120.00    1350.0   Millions      INR
26       129    100.00     410.0   Millions      INR
27       130    850.00    8540.0   Millions      INR
28       131      1.00       5.9   Billions      INR
29       132      2.00       3.6   Billions      INR
30       133      5.50      12.0   Billions      INR
31       134      1.80       6.5   Billions      INR
32       135    250.00    3409.0   Millions      INR
33       136    900.00   11690.0   Millions      INR
34       137    216.70     370.6   Millions      USD
35       138    177.00     714.4   Millions      USD
36       139      1.80       3.1   Billions      INR
37       140    500.00     950.0   Millions      INR
38       406     30.00     350.0   Millions      INR
39       412    160.00     836.8   Millions      USD

In [6]:
# merging 2 excel dataframes
df_merged=pd.merge(df_m,df,on="movie_id")
print(df_merged)

    movie_id                                        title   industry  \
0        101                             K.G.F: Chapter 2  Bollywood
1        102  Doctor Strange in the Multiverse of Madness  Hollywood
2        103                        Thor: The Dark World   Hollywood
3        104                              Thor: Ragnarok   Hollywood
4        105                      Thor: Love and Thunder   Hollywood
5        107                  Dilwale Dulhania Le Jayenge  Bollywood
6        108                                     3 Idiots  Bollywood
7        109                     Kabhi Khushi Kabhie Gham  Bollywood
8        110                             Bajirao Mastani   Bollywood
9        111                     The Shawshank Redemption  Hollywood
10       113                                 Interstellar  Hollywood
11       115                     The Pursuit of Happyness  Hollywood
12       116                                    Gladiator  Hollywood
13       117                                      Titanic  Hollywood
14       118                        It's a Wonderful Life  Hollywood
15       119                                       Avatar  Hollywood
16       120                                The Godfather  Hollywood
17       121                              The Dark Knight  Hollywood
18       122                             Schindler's List  Hollywood
19       123                                Jurassic Park  Hollywood
20       124                                     Parasite  Hollywood
21       125                            Avengers: Endgame  Hollywood
22       126                       Avengers: Infinity War  Hollywood
23       127                              Pather Panchali  Bollywood
24       128                             Taare Zameen Par  Bollywood
25       129                          Munna Bhai M.B.B.S.  Bollywood
26       130                                           PK  Bollywood
27       131                                        Sanju  Bollywood
28       132                    Pushpa: The Rise - Part 1  Bollywood
29       133                                          RRR  Bollywood
30       134                     Baahubali: The Beginning  Bollywood
31       135                            The Kashmir Files  Bollywood
32       136                            Bajrangi Bhaijaan  Bollywood
33       137           Captain America: The First Avenger  Hollywood
34       138          Captain America: The Winter Soldier  Hollywood
35       139                                       Race 3  Bollywood
36       140                                    Shershaah  Bollywood

    release_year  imdb_rating                     studio  language_id  \
0           2022          8.4              Hombale Films            3
1           2022          7.0             Marvel Studios            5
2           2013          6.8             Marvel Studios            5
3           2017          7.9             Marvel Studios            5
4           2022          6.8             Marvel Studios            5
5           1995          8.0             Yash Raj Films            1
6           2009          8.4         Vinod Chopra Films            1
7           2001          7.4         Dharma Productions            1
8           2015          7.2                        NaN            1
9           1994          9.3  Castle Rock Entertainment            5
10          2014          8.6      Warner Bros. Pictures            5
11          2006          8.0          Columbia Pictures            5
12          2000          8.5       Universal Pictures              5
13          1997          7.9         Paramount Pictures            5
14          1946          8.6              Liberty Films            5
15          2009          7.8           20th Century Fox            5
16          1972          9.2         Paramount Pictures            5
17          2008          9.0                    Syncopy            5
18          1993          9.0         Universal Pictures            5
19          1993          8.2         Universal Pictures            5
20          2019          8.5                        NaN            5
21          2019          8.4             Marvel Studios            5
22          2018          8.4             Marvel Studios            5
23          1955          8.3  Government of West Bengal            7
24          2007          8.3                        NaN            1
25          2003          8.1   Vinod Chopra Productions            1
26          2014          8.1         Vinod Chopra Films            1
27          2018          NaN         Vinod Chopra Films            1
28          2021          7.6        Mythri Movie Makers            2
29          2022          8.0          DVV Entertainment            2
30          2015          8.0           Arka Media Works            2
31          2022          8.3                Zee Studios            1
32          2015          8.1          Salman Khan Films            1
33          2011          6.9             Marvel Studios            5
34          2014          7.8             Marvel Studios            5
35          2018          1.9          Salman Khan Films            1
36          2021          8.4         Dharma Productions            1

      budget   revenue       unit currency
0       1.00      12.5   Billions      INR
1     200.00     954.8   Millions      USD
2     165.00     644.8   Millions       $$
3     180.00     854.0   Millions  Dollars
4     250.00     670.0   Millions      USD
5     400.00    2000.0   Millions      INR
6     550.00    4000.0   Millions      INR
7     390.00    1360.0   Millions      INR
8       1.40       3.5   Billions      INR
9      25.00      73.3   Millions      USD
10    165.00     701.8   Millions      USD
11     55.00     307.1   Millions      USD
12    103.00     460.5   Millions      USD
13    200.00    2202.0   Millions      USD
14      3.18       3.3   Millions      USD
15    237.00    2847.0   Millions      USD
16      7.20     291.0   Millions      USD
17    185.00    1006.0   Millions      USD
18     22.00     322.2   Millions      USD
19     63.00    1046.0   Millions      USD
20     15.50     263.1   Millions      USD
21    400.00    2798.0   Millions      USD
22    400.00    2048.0   Millions      USD
23  70000.00  100000.0  Thousands      INR
24    120.00    1350.0   Millions      INR
25    100.00     410.0   Millions      INR
26    850.00    8540.0   Millions      INR
27      1.00       5.9   Billions      INR
28      2.00       3.6   Billions      INR
29      5.50      12.0   Billions      INR
30      1.80       6.5   Billions      INR
31    250.00    3409.0   Millions      INR
32    900.00   11690.0   Millions      INR
33    216.70     370.6   Millions      USD
34    177.00     714.4   Millions      USD
35      1.80       3.1   Billions      INR
36    500.00     950.0   Millions      INR

In [7]:
df_merged.to_excel("merged.xlsx")

In [5]:
# creating excel dataframes
df_1=pd.DataFrame({
    'name':["apple","billi","kutta"],
    'id':[1,2,3]
})
print(df_1)

    name  id
0  apple   1
1  billi   2
2  kutta   3

In [6]:
df_2=pd.DataFrame({
    'name':["apple","billi","kutta"],
    'occ':["manager","employee","boss"]
})

print(df_2)

    name       occ
0  apple   manager
1  billi  employee
2  kutta      boss

In [7]:
# saving two dataframes to excel files
with pd.ExcelWriter("NEWEXCEL.xlsx") as writer:
    df_1.to_excel(writer,sheet_name="names")
    df_2.to_excel(writer,sheet_name="occupation")